Cargo.lock
Cargo.toml
src/context.rs
src/gtfs_rt.rs
src/main.rs
src/server.rs
src/siri_model.rs
src/stop_monitoring.rs
src/stoppoints_discovery.rs
tests/stop_point_discovery_test.rs

move the gtfs raw structures + computed ressources to a `Data` container
(I couldn't find a less meaningfull name, sorry...)
wrap all this in Arc<Mutex> to share it between the threads
Note: It depends on https://github.com/rust-transit/gtfs-structure/pull/8, and will need to be updated after the merge

read the gtfs only once

---

src/context.rs
src/gtfs_rt.rs
src/gtfs_rt_utils.rs
src/lib.rs
src/stop_monitoring.rs

for the moment it's synchronous, and some parts still need to be implemented.
[ ] fill the `get_model_update` method to create a `ModelUpdate` from a gtfs_rt
[ ] read the new `RealTimeConnection` fields to fill the `SiriResponse`
I open early this PR to get early architecture feedback.

Synchronous apply of the GTFS-RT

---

Cargo.lock
Cargo.toml
src/context.rs
src/gtfs_rt.rs
src/gtfs_rt_utils.rs
src/lib.rs
src/siri_model.rs
src/stop_monitoring.rs
tests/stop_monitoring_test.rs

This is a first minimal working version for realtime info in stop monitoring.
depends on #37 
It has been tested with [grenoble's realtime](https://data.metromobilite.fr/api/gtfs-rt/GAM/trip-update) data and seems to work.
TODO (but they might be for others PR):

Adding realtime information in StopMonitoring

---

src/stop_monitoring.rs

this way it's not a mandatory parameter anymore

add a default value for datafreshness

---

src/context.rs
src/dataset_handler_actor.rs
src/gtfs_rt.rs
src/gtfs_rt_utils.rs
src/lib.rs
src/main.rs
src/server.rs
src/status.rs
src/stop_monitoring.rs
src/stoppoints_discovery.rs
src/update_actors.rs
tests/utils/mod.rs

The problem with the current implementation is that all the work is done
by the `Context` (now called `Dataset` :wink:) Actor and thus all the
webservice has become mainly single threaded...
This PR introduces:
* a `DatasetActor` whose only job is to give an Arc (a shared pointer) to
a `Dataset`
* a `BaseScheduleReloader` Actor whose job is to periodically reload the
data, and send the newly created `Dataset` to the `DatasetActor` for
updating.
Since the `DatasetActor` works in its own thread, this way we'll be able
to remove all the `Mutex`, and still have a multithread service!
For the moment all the Arcs have not been removed, because we still need
the mutate the `Dataset` when receiving a gtfs-rt, but this will be
changed in another PR.
Do not hesitate if you have better ideas for the …

New shot at the actor model.

---

src/actors/realtime_update_actors.rs
src/routes/stop_monitoring.rs
src/siri_model.rs

the specification is not straightforward, but this add a bit more fields
to the Siri's response
I don't think it fixes #20 , but It is a step in the right direction.
After this, maybe we'll be able to move the siri_model to it's own https://github.com/rust-transit/ crate

More siri fields

---

README.md
src/server.rs
tests/stop_monitoring_test.rs
tests/stop_point_discovery_test.rs

I think it is nice to add a bit more information in the readme.
I tried to:
* add some general context on the API
* list all the routes
* add a bit of details on the general architecture since we had several iteration on this.
when documenting the routes, I found that the siri lite routes were better when nested behind `/siri-lite`, so I changed this too
fixes #50

Add more information in the readme

---

README.md
src/server.rs
tests/multiple_gtfs_rts.rs
tests/stop_monitoring_test.rs
tests/stop_point_discovery_test.rs

the routes were not respecting the [siri specification](http://www.normes-donnees-tc.org/wp-content/uploads/2018/10/Proposition-Profil-SIRI-Lite-initial-v1-3.pdf)
This is a breaking change, but I think we don't have any user for the moment, so we should do this right now.
Change:
`/{id}/siri-lite/stop_monitoring.json` -> `/{id}/siri/2.0/stop-monitoring.json` 
(same for stoppoints-discovery)
also changed `/{id}/gtfs_rt` to `/{id}/gtfs-rt` for API coherence
fixes https://github.com/etalab/transpo-rt/issues/64
:warning: We need to update transport site after this is merged :warning:

breaking change: change routes for siri coherence

---

Cargo.lock
Cargo.toml
src/routes/stop_monitoring.rs
src/siri_model.rs
src/utils.rs
tests/stop_monitoring_test.rs

add 2 filters: 
* MaximumStopVisits
* PreviewInterval
fill the field operator_ref
I updated #19  with the remaining params

stick a bit more to the siri spec

---

src/actors/realtime_update_actors.rs
src/model_update.rs
src/tests/update_model_test.rs

stick a bit more to the gtfs_rt spec.
the stop_sequence is mandatory for the moment though, we'll check if some people do not give it

stop_id in stop_time_update is not mandatory

---

Cargo.lock
Cargo.toml
src/actors/realtime_update_actors.rs
src/actors/update_actors.rs
src/datasets.rs
src/main.rs
src/model_update.rs
src/server.rs
src/tests/update_model_test.rs

sentry can be activated with the --sentry parameter (or TRANSPO_RT_SENTRY env var)
if activated sentry will now report:
* the 5xx errors
* the gtfs_rt reloading errors
* a warning if some stop_id are incoherent
for the moment for the gtfs_rt problems, we add the dataset id as a tag to the error. we'll need to see if we need more information
some more check will need to be added in the future.
Note: it's after #73 else there is some conflicts

add basic sentry

---

Cargo.lock
Cargo.toml
src/actors/realtime_update_actors.rs
src/actors/update_actors.rs
src/lib.rs
src/main.rs
src/server.rs
src/utils.rs
tests/general_message_test.rs
tests/list_datasets_test.rs
tests/multiple_gtfs_rts.rs
tests/openapi_test.rs
tests/stop_monitoring_test.rs
tests/stop_point_discovery_test.rs
tests/utils/mod.rs

now the log are like:
```
May 14 14:37:47.904 INFO Starting server on 0.0.0.0:8080
May 14 14:37:47.905 INFO Starting the context actor
May 14 14:37:47.905 INFO Starting the base schedule updater actor,
instance: metromobilite
May 14 14:37:47.905 INFO Starting the realtime updater actor, instance:
metromobilite
May 14 14:37:47.905 INFO Starting the context actor
May 14 14:37:47.906 INFO Starting the base schedule updater actor,
instance: poitiers
May 14 14:37:47.906 INFO Starting the realtime updater actor, instance:
poitiers
May 14 14:37:47.906 INFO fetching a gtfs_rt, instance: metromobilite
May 14 14:37:48.462 INFO 2394 connections have been updated with trip
updates, instance: metromobilite
May 14 14:37:48.463 INFO realtime reloaded, instance: metromobilite
May 14 14:37:48.464 INFO …
```

add structured logging to have the instance name in log

---

src/model_update.rs
src/routes/open_api.rs

fixes #59
implements the "Alternative trip matching" the [gtfs-rt specification](https://developers.google.com/transit/gtfs-realtime/guides/trip-updates) when we cannot find a corresponding VJ.
Note: with this the [auxerre dataset](https://static.data.gouv.fr/resources/reseau-de-transports-en-commun-de-la-communaute-dagglomeration-de-lauxerrois/20190605-094228/gtfs.zip) works (`344 connections have been updated with trip updates,`) even if it seems that the GTFS-RT is not completly synced with the GTFS (some routes are missing and some stop_time are not the same)

add a relaxed way to match a trip 

---

src/actors/update_actors.rs
src/datasets.rs
src/server.rs

the base schedules are reloading once per day. This operation can fail, if for example the external  erver is temporarily unavailable.
If the reloading fails, we try it again 5mn later, while just keeping the old dataset.
It is not exponential back-off nor do we particularly monitor those fails. If they become more troublesome we could implement more advanced techniques.

handle errors while reloading base schedule

---

src/routes/stoppoints_discovery.rs
tests/openapi_test.rs
tests/stop_point_discovery_test.rs

even if it's not in siri-lite it's usefull not to overload the server

add a limit to the stoppoint discovery query

---

src/datasets.rs
src/model_update.rs
src/utils.rs

in wrongly formatted data, a vehicle journey can be attached to an unknown calendar. We used to stop the program on such case, but now we only skip the vehicle journey.

skipping unknown calendar

---

src/main.rs

because the logger wasn't there anymore (already dropped).

actix was panicking during ctrl+c due to slog logger

---

src/main.rs

add trailing slash, this way `/toto` is the same as `/toto/`
add a nicer 404 with a custom message

Cleanup api

---

src/routes/links.rs
src/routes/open_api.rs
src/server.rs
tests/entry_point_test.rs
tests/utils/mod.rs

The [actix doc](https://docs.rs/actix-web/3.2.0/actix_web/middleware/normalize/enum.TrailingSlash.html#variant.Always) states that the routes need to be mounted with a trailing slash and since that was not the case some routes were broken

fixes trailing slashes handling

---

README.md
src/actors/dataset_handler_actor.rs
src/actors/realtime_update_actors.rs
src/actors/update_actors.rs
src/datasets.rs
src/routes/general_message.rs
src/routes/open_api.rs
src/routes/siri.rs
src/routes/status.rs
src/routes/stop_monitoring.rs
src/routes/stoppoints_discovery.rs
src/server.rs
tests/entry_point_test.rs
tests/gtfs_error_test.rs
tests/utils/mod.rs

As seen in #107, if at start time, a given resource is not available, it will be removed from the available resources forever.
In this PR, we instead implement a mechanism to ensure the initial failure has a chance to recover later.
It must be noted thought that it will currently take 24 hours before the dataset is retried (see #111), something we will improve in a separate PR.

Do not unregister datasets with a 404'ed base schedule at time of startup

---

src/extractors/dataset_wrapper.rs
src/extractors/mod.rs
src/lib.rs
src/routes/general_message.rs
src/routes/gtfs_rt.rs
src/routes/siri.rs
src/routes/status.rs
src/routes/stop_monitoring.rs
src/routes/stoppoints_discovery.rs

add 2 wrappers that provide a convenient way to get a `RealTimeDataset` / `Dataset` from an actix route.
They handle all the `DatasetActor` querying and the error handling.
```rust
use transpo_rt::extractors::RealTimeDatasetWrapper;
pub async fn a_route(rt_dataset_wrapper: RealTimeDatasetWrapper) -> actix_web::Result<()> {
let gtfs_rt = &rt_dataset_wrapper.gtfs_rt; // can be used as if it was a RealTimeDataset
let dataset = rt_dataset_wrapper.get_base_schedule_dataset()?;
Ok(())
}
```

Ease way to get RealTimeDataset / Dataset from an actix route
